Homework_11_v1
eugene-okulik/yulmiro pull request #11
Opened 2024-12-12 09:54 UTC by Yulmiro23

2024-12-12 10:09 UTC, Yulmiro23 commented
Не понимаю, почему не проходит форматирование( там одинаковые строчки заполнения объекта, на одну почему-то ругается, не понимаю

2024-12-13 07:27 UTC, eugene-okulik approved these changes

2024-12-13 07:27 UTC, eugene-okulik commented on homework/yulia_mironova/Homework_11/Task.py
> +      f'{', зарезервирована' if book_1.reserved else ''}')
Странно, что ругается только на одну. Здесь фишка в совместимости разных версий питона. В новой версии уже можно делать так, как ты делаешь, но раньше нельзя было и линт это отмечает. Заморочка в кавычках - у тебя они везде одинаковые и питон предыдущей версии не смог бы с этим работать. Лучше пока что, раз это только в одной версии есть, пользоваться по-старому
```python
print(f'Название: {book_1.title}, Автор: {book_1.author}, страниц: {book_1.pages}, материал: {book_1.material}'
      f"{', зарезервирована' if book_1.reserved else ''}")
```

2024-12-13 07:27 UTC, eugene-okulik commented on homework/yulia_mironova/Homework_11/Task.py
> +      f'предмет: {textbook_3.subject}, класс {textbook_3.group}{', зарезервирована' if textbook_3.reserved else ''}')
Ну и все эти строчки - это повторение одного и того же кода. Можно для этого сделать или функции или даже методы

2024-12-13 07:28 UTC, eugene-okulik requested changes
Случайно аппрувнул, исправляюсь )))

2024-12-14 10:30 UTC, eugene-okulik approved these changes
:+1:

2024-12-14 10:30 UTC, merged